const express=require('express');
const subscriptionCRUDController=require('./../controllers/subscriptionsCRUDController');
const adminAuthConroller=require('./../controllers/adminAuthConroller');
const subscriptionDashRoute=express.Router();
subscriptionDashRoute.use(adminAuthConroller.protect);
subscriptionDashRoute.get('/allsubscriptionstypes',subscriptionCRUDController.getAllSubscriptionsTypes);
subscriptionDashRoute.post('/createnewsubscriptionstype',subscriptionCRUDController.createSubscriptionType);
subscriptionDashRoute.patch('/updatesubscriptionstype/:id',subscriptionCRUDController.updateSubscriptionTypes);
subscriptionDashRoute.delete('/deletesubscriptionstype/:id',subscriptionCRUDController.deleteSubscriptionType);
subscriptionDashRoute.get('/subscriptiontype/:id',subscriptionCRUDController.getSubscriptionsType);
module.exports=subscriptionDashRoute;
